name: go_app

services:
  psql:
    env_file:
      - .env
    image: postgres:16-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    container_name: psql
    networks:
      - net

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    environment:
      - CLICKHOUSE_DB=app
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=
    volumes:
      - ch-data:/var/lib/clickhouse
      - ./clickhouse-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "8123:8123"
      - "9000:9000"
    restart: unless-stopped
    container_name: clickhouse
    networks:
      - net

  elasticsearch:
    image: elasticsearch:9.5.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:3000
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped
    container_name: elasticsearch
    networks:
      - net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped
    container_name: zookeeper
    networks:
      - net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    restart: unless-stopped
    container_name: kafka
    networks:
      - net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    container_name: redis
    networks:
      - net

volumes:
  pg-data:
    driver: local
  ch-data:
    driver: local
  es-data:
    driver: local

networks:
  net:
    driver: bridge

